<a href="https://colab.research.google.com/github/RajivDalal/ML_practice/blob/main/Pandas_(Day_4_5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas
- Library that helps to manipulate and analyze data
- Provides data frames and series

In [ ]:
import numpy as np
import pandas as pd

# Series

In [ ]:
data = ["Rajiv",20,"ab",2004]
s=pd.Series(data)
s

<class 'pandas.core.series.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: None
Non-Null Count  Dtype
--------------  -----
4 non-null      object
dtypes: object(1)
memory usage: 160.0+ bytes

0    Rajiv
1       20
2       ab
3     2004
dtype: object

In [ ]:
s = pd.Series(np.random.rand(15))
print(s)
print(s[3])

0     0.805918
1     0.303227
2     0.248495
3     0.821893
4     0.952607
5     0.859422
6     0.088104
7     0.764004
8     0.684830
9     0.378152
10    0.939642
11    0.144013
12    0.836477
13    0.234993
14    0.473348
dtype: float64
0.8218929120945124

In [ ]:
print(s[0:2])

0    0.805918
1    0.303227
dtype: float64

In [ ]:
print(s.argmax())
print(s.argmin())
print(s.mean())
print(s.max())
print(s.min())
print(s.size) #s.count() also same

4
6
0.5690083423615261
0.9526067236987713
0.08810447220148532
15

In [ ]:
print(s.head()) #Top 5 records
print(s.tail()) #Bottom 5 records

0    0.805918
1    0.303227
2    0.248495
3    0.821893
4    0.952607
dtype: float64
10    0.939642
11    0.144013
12    0.836477
13    0.234993
14    0.473348
dtype: float64

In [ ]:
print(s.describe())

count    15.000000
mean      0.569008
std       0.311025
min       0.088104
25%       0.275861
50%       0.684830
75%       0.829185
max       0.952607
dtype: float64

# Dataframes

In [ ]:
s1 = pd.Series(np.random.rand(5))
s2 = pd.Series(np.random.rand(5))
print(s1,s2,sep="\n")

0    0.942383
1    0.835541
2    0.792617
3    0.219832
4    0.563822
dtype: float64
0    0.615419
1    0.059494
2    0.301997
3    0.999438
4    0.141054
dtype: float64

In [ ]:
#Creating dataframes using series
a = pd.DataFrame((s1,s2))
print(a)

          0         1         2         3         4
0  0.942383  0.835541  0.792617  0.219832  0.563822
1  0.615419  0.059494  0.301997  0.999438  0.141054

In [ ]:
#Creating dataframes using dictionaries
d1 = {"name":"Rajiv","age":20}
d2 = {"name":"Srishti","age":21}

b = pd.DataFrame((d1,d2))
print(b)

      name  age
0    Rajiv   20
1  Srishti   21

In [ ]:
b["gender"]=["Male","Female"]
print(b)

      name  age  gender
0    Rajiv   20    Male
1  Srishti   21  Female

#iloc & loc functions
- dataframe_name.iloc[row_index,column_index]
- dataframe_name.iloc[row_name,column_name]

In [ ]:
print(b.iloc[0,1])
print(b.iloc[0:2,1:])

20
   age  gender
0   20    Male
1   21  Female

In [ ]:
print(b.loc[:,["name","gender"]])

      name  gender
0    Rajiv    Male
1  Srishti  Female

In [ ]:
print(b.shape)
print(b.columns)

(2, 3)
Index(['name', 'age', 'gender'], dtype='object')

In [ ]:
print(b.isnull(),end="\n\n")
print(b.isnull().sum())

    name    age  gender
0  False  False   False
1  False  False   False

name      0
age       0
gender    0
dtype: int64

In [ ]:
b.rename(columns={"exp":"age"},inplace=True)
print(b)

      name  age  gender
0    Rajiv   20    Male
1  Srishti   21  Female

In [ ]:
#Dropping a column
b.drop(columns=["gender"],axis=1) #axis=0 for rows

      name  age
0    Rajiv   20
1  Srishti   21

In [ ]:
b.duplicated()

0    False
1    False
dtype: bool

# Reading Files

In [ ]:
data = pd.read_csv("/content/mtcars.csv")
data

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
data.head()
data.tail

               model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3

   carb
0     4
1     4
2     1
3     1
4     2
             model   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4

    carb
27     2
28     4
29     6
30     8
31     2

In [ ]:
data.tail()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2